# -*- mode: ruby -*-

# vi: set ft=ruby :

boxes = [
    {
        :name => "serverxcard",
        :eth1 => "192.168.10.11",
        :eth2 => "192.168.0.150",
        :mem => "512",
        :cpu => "1"
    }
]

Vagrant.configure(2) do |config|

  config.vm.box = "xcardserver"

  # Turn off shared folders
  config.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=775', 'fmode=775'], disable:true


  #config.vm.synced_folder "~/Virtual/webrtc", "/home/vagrant", :mount_options => ['dmode=775', 'fmode=775']
  config.vm.synced_folder "/NTex/Web/openCard", "/srv/www/GiftCard", :mount_options => ['dmode=777', 'fmode=777']
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]

      config.vm.provider "virtualbox" do |v|
        #v.gui = true
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        v.name = opts[:name]
      end
      config.vm.network "public_network",ip: opts[:eth2]
      config.vm.network "private_network", ip: opts[:eth1]
    end
  end
end
